0 0 dataAuditErrors
1 0 non45Errors
2 0 offGridErrors
234 0 offGridShapeErrors: off grid polygon on layer Bondpad
236 0 offGridShapeErrors: off grid polygon on layer CapMetal
238 0 offGridShapeErrors: off grid polygon on layer Cont
240 0 offGridShapeErrors: off grid polygon on layer ESDdummy
242 0 offGridShapeErrors: off grid polygon on layer IND2dummy
244 0 offGridShapeErrors: off grid polygon on layer IND3dummy
246 0 offGridShapeErrors: off grid polygon on layer INDdummy
248 0 offGridShapeErrors: off grid polygon on layer M1Resdum
250 0 offGridShapeErrors: off grid polygon on layer M2Resdum
252 0 offGridShapeErrors: off grid polygon on layer M3Resdum
254 0 offGridShapeErrors: off grid polygon on layer M4Resdum
256 0 offGridShapeErrors: off grid polygon on layer M5Resdum
258 0 offGridShapeErrors: off grid polygon on layer M6Resdum
260 0 offGridShapeErrors: off grid polygon on layer M7Resdum
262 0 offGridShapeErrors: off grid polygon on layer M8Resdum
264 0 offGridShapeErrors: off grid polygon on layer M9Resdum
266 0 offGridShapeErrors: off grid polygon on layer Metal1_d
268 0 offGridShapeErrors: off grid polygon on layer Metal1_f
270 0 offGridShapeErrors: off grid polygon on layer Metal1_n
272 0 offGridShapeErrors: off grid polygon on layer Metal1_p
274 0 offGridShapeErrors: off grid polygon on layer Metal1_slot
276 0 offGridShapeErrors: off grid polygon on layer Metal2_d
278 0 offGridShapeErrors: off grid polygon on layer Metal2_f
280 0 offGridShapeErrors: off grid polygon on layer Metal2_n
282 0 offGridShapeErrors: off grid polygon on layer Metal2_p
284 0 offGridShapeErrors: off grid polygon on layer Metal2_slot
286 0 offGridShapeErrors: off grid polygon on layer Metal3_d
288 0 offGridShapeErrors: off grid polygon on layer Metal3_f
290 0 offGridShapeErrors: off grid polygon on layer Metal3_n
292 0 offGridShapeErrors: off grid polygon on layer Metal3_p
294 0 offGridShapeErrors: off grid polygon on layer Metal3_slot
296 0 offGridShapeErrors: off grid polygon on layer Metal4_d
298 0 offGridShapeErrors: off grid polygon on layer Metal4_f
300 0 offGridShapeErrors: off grid polygon on layer Metal4_n
302 0 offGridShapeErrors: off grid polygon on layer Metal4_p
304 0 offGridShapeErrors: off grid polygon on layer Metal4_slot
306 0 offGridShapeErrors: off grid polygon on layer Metal5_d
308 0 offGridShapeErrors: off grid polygon on layer Metal5_f
310 0 offGridShapeErrors: off grid polygon on layer Metal5_n
312 0 offGridShapeErrors: off grid polygon on layer Metal5_p
314 0 offGridShapeErrors: off grid polygon on layer Metal5_slot
316 0 offGridShapeErrors: off grid polygon on layer Metal6_d
318 0 offGridShapeErrors: off grid polygon on layer Metal6_f
320 0 offGridShapeErrors: off grid polygon on layer Metal6_n
322 0 offGridShapeErrors: off grid polygon on layer Metal6_p
324 0 offGridShapeErrors: off grid polygon on layer Metal6_slot
326 0 offGridShapeErrors: off grid polygon on layer Metal7_d
328 0 offGridShapeErrors: off grid polygon on layer Metal7_f
330 0 offGridShapeErrors: off grid polygon on layer Metal7_n
332 0 offGridShapeErrors: off grid polygon on layer Metal7_p
334 0 offGridShapeErrors: off grid polygon on layer Metal7_slot
336 0 offGridShapeErrors: off grid polygon on layer Metal8_d
338 0 offGridShapeErrors: off grid polygon on layer Metal8_f
340 0 offGridShapeErrors: off grid polygon on layer Metal8_n
342 0 offGridShapeErrors: off grid polygon on layer Metal8_p
344 0 offGridShapeErrors: off grid polygon on layer Metal8_slot
346 0 offGridShapeErrors: off grid polygon on layer Metal9_d
348 0 offGridShapeErrors: off grid polygon on layer Metal9_f
350 0 offGridShapeErrors: off grid polygon on layer Metal9_n
352 0 offGridShapeErrors: off grid polygon on layer Metal9_p
354 0 offGridShapeErrors: off grid polygon on layer Metal9_slot
356 0 offGridShapeErrors: off grid polygon on layer NPNdummy
358 0 offGridShapeErrors: off grid polygon on layer Nburied
360 0 offGridShapeErrors: off grid polygon on layer Nhvt
362 0 offGridShapeErrors: off grid polygon on layer Nimp
364 0 offGridShapeErrors: off grid polygon on layer Nwell
366 0 offGridShapeErrors: off grid polygon on layer Nzvt
368 0 offGridShapeErrors: off grid polygon on layer Oxide
370 0 offGridShapeErrors: off grid polygon on layer Oxide_thk
372 0 offGridShapeErrors: off grid polygon on layer PNPdummy
374 0 offGridShapeErrors: off grid polygon on layer Phvt
376 0 offGridShapeErrors: off grid polygon on layer Pimp
378 0 offGridShapeErrors: off grid polygon on layer Poly
380 0 offGridShapeErrors: off grid polygon on layer Psub
382 0 offGridShapeErrors: off grid polygon on layer ResWdum
384 0 offGridShapeErrors: off grid polygon on layer Resdum
386 0 offGridShapeErrors: off grid polygon on layer SiProt
388 0 offGridShapeErrors: off grid polygon on layer Via1
390 0 offGridShapeErrors: off grid polygon on layer Via2
392 0 offGridShapeErrors: off grid polygon on layer Via3
394 0 offGridShapeErrors: off grid polygon on layer Via4
396 0 offGridShapeErrors: off grid polygon on layer Via5
398 0 offGridShapeErrors: off grid polygon on layer Via6
400 0 offGridShapeErrors: off grid polygon on layer Via7
402 0 offGridShapeErrors: off grid polygon on layer Via8
403 0 non45 degree polygon on layer Bondpad
404 0 non45 degree polygon on layer CapMetal
406 0 non45 degree polygon on layer Cont
408 0 non45 degree polygon on layer ESDdummy
410 0 non45 degree polygon on layer IND2dummy
412 0 non45 degree polygon on layer IND3dummy
413 0 non45 degree polygon on layer INDdummy
415 0 non45 degree polygon on layer M1Resdum
417 0 non45 degree polygon on layer M2Resdum
419 0 non45 degree polygon on layer M3Resdum
421 0 non45 degree polygon on layer M4Resdum
423 0 non45 degree polygon on layer M5Resdum
425 0 non45 degree polygon on layer M6Resdum
427 0 non45 degree polygon on layer M7Resdum
429 0 non45 degree polygon on layer M8Resdum
431 0 non45 degree polygon on layer M9Resdum
432 0 non45 degree polygon on layer Metal1_d
434 0 non45 degree polygon on layer Metal1_f
436 0 non45 degree polygon on layer Metal1_n
437 0 non45 degree polygon on layer Metal1_p
439 0 non45 degree polygon on layer Metal1_slot
440 0 non45 degree polygon on layer Metal2_d
442 0 non45 degree polygon on layer Metal2_f
444 0 non45 degree polygon on layer Metal2_n
445 0 non45 degree polygon on layer Metal2_p
447 0 non45 degree polygon on layer Metal2_slot
448 0 non45 degree polygon on layer Metal3_d
450 0 non45 degree polygon on layer Metal3_f
452 0 non45 degree polygon on layer Metal3_n
453 0 non45 degree polygon on layer Metal3_p
455 0 non45 degree polygon on layer Metal3_slot
456 0 non45 degree polygon on layer Metal4_d
458 0 non45 degree polygon on layer Metal4_f
460 0 non45 degree polygon on layer Metal4_n
461 0 non45 degree polygon on layer Metal4_p
463 0 non45 degree polygon on layer Metal4_slot
464 0 non45 degree polygon on layer Metal5_d
466 0 non45 degree polygon on layer Metal5_f
468 0 non45 degree polygon on layer Metal5_n
469 0 non45 degree polygon on layer Metal5_p
471 0 non45 degree polygon on layer Metal5_slot
472 0 non45 degree polygon on layer Metal6_d
474 0 non45 degree polygon on layer Metal6_f
476 0 non45 degree polygon on layer Metal6_n
477 0 non45 degree polygon on layer Metal6_p
479 0 non45 degree polygon on layer Metal6_slot
480 0 non45 degree polygon on layer Metal7_d
482 0 non45 degree polygon on layer Metal7_f
484 0 non45 degree polygon on layer Metal7_n
485 0 non45 degree polygon on layer Metal7_p
487 0 non45 degree polygon on layer Metal7_slot
488 0 non45 degree polygon on layer Metal8_d
490 0 non45 degree polygon on layer Metal8_f
492 0 non45 degree polygon on layer Metal8_n
493 0 non45 degree polygon on layer Metal8_p
495 0 non45 degree polygon on layer Metal8_slot
496 0 non45 degree polygon on layer Metal9_d
498 0 non45 degree polygon on layer Metal9_f
500 0 non45 degree polygon on layer Metal9_n
501 0 non45 degree polygon on layer Metal9_p
503 0 non45 degree polygon on layer Metal9_slot
505 0 non45 degree polygon on layer NPNdummy
506 0 non45 degree polygon on layer Nburied
508 0 non45 degree polygon on layer Nhvt
509 0 non45 degree polygon on layer Nimp
510 0 non45 degree polygon on layer Nwell
512 0 non45 degree polygon on layer Nzvt
514 0 non45 degree polygon on layer Oxide
516 0 non45 degree polygon on layer Oxide_thk
518 0 non45 degree polygon on layer PNPdummy
520 0 non45 degree polygon on layer Phvt
521 0 non45 degree polygon on layer Pimp
522 0 non45 degree polygon on layer Poly
523 0 non45 degree polygon on layer Psub
525 0 non45 degree polygon on layer ResWdum
527 0 non45 degree polygon on layer Resdum
529 0 non45 degree polygon on layer SiProt
531 0 non45 degree polygon on layer Via1
533 0 non45 degree polygon on layer Via2
535 0 non45 degree polygon on layer Via3
537 0 non45 degree polygon on layer Via4
539 0 non45 degree polygon on layer Via5
541 0 non45 degree polygon on layer Via6
543 0 non45 degree polygon on layer Via7
545 0 non45 degree polygon on layer Via8
546 0 acute angle on layer Bondpad
547 0 acute angle on layer CapMetal
548 0 acute angle on layer ESDdummy
549 0 acute angle on layer IND2dummy
550 0 acute angle on layer IND3dummy
551 0 acute angle on layer INDdummy
552 0 acute angle on layer M1Resdum
553 0 acute angle on layer M2Resdum
554 0 acute angle on layer M3Resdum
555 0 acute angle on layer M4Resdum
556 0 acute angle on layer M5Resdum
557 0 acute angle on layer M6Resdum
558 0 acute angle on layer M7Resdum
559 0 acute angle on layer M8Resdum
560 0 acute angle on layer M9Resdum
561 0 acute angle on layer Metal1_d
562 0 acute angle on layer Metal1_f
563 0 acute angle on layer Metal1_n
564 0 acute angle on layer Metal1_p
565 0 acute angle on layer Metal1_slot
566 0 acute angle on layer Metal2_d
567 0 acute angle on layer Metal2_f
568 0 acute angle on layer Metal2_n
569 0 acute angle on layer Metal2_p
570 0 acute angle on layer Metal2_slot
571 0 acute angle on layer Metal3_d
572 0 acute angle on layer Metal3_f
573 0 acute angle on layer Metal3_n
574 0 acute angle on layer Metal3_p
575 0 acute angle on layer Metal3_slot
576 0 acute angle on layer Metal4_d
577 0 acute angle on layer Metal4_f
578 0 acute angle on layer Metal4_n
579 0 acute angle on layer Metal4_p
580 0 acute angle on layer Metal4_slot
581 0 acute angle on layer Metal5_d
582 0 acute angle on layer Metal5_f
583 0 acute angle on layer Metal5_n
584 0 acute angle on layer Metal5_p
585 0 acute angle on layer Metal5_slot
586 0 acute angle on layer Metal6_d
587 0 acute angle on layer Metal6_f
588 0 acute angle on layer Metal6_n
589 0 acute angle on layer Metal6_p
590 0 acute angle on layer Metal6_slot
591 0 acute angle on layer Metal7_d
592 0 acute angle on layer Metal7_f
593 0 acute angle on layer Metal7_n
594 0 acute angle on layer Metal7_p
595 0 acute angle on layer Metal7_slot
596 0 acute angle on layer Metal8_d
597 0 acute angle on layer Metal8_f
598 0 acute angle on layer Metal8_n
599 0 acute angle on layer Metal8_p
600 0 acute angle on layer Metal8_slot
601 0 acute angle on layer Metal9_d
602 0 acute angle on layer Metal9_f
603 0 acute angle on layer Metal9_n
604 0 acute angle on layer Metal9_p
605 0 acute angle on layer Metal9_slot
606 0 acute angle on layer NPNdummy
607 0 acute angle on layer Nhvt
608 0 acute angle on layer PNPdummy
609 0 acute angle on layer Phvt
610 0 acute angle on layer Psub
611 0 acute angle on layer ResWdum
612 0 acute angle on layer Resdum
638 0 NZVT.X.4: Only one Oxide region may be in an Nzvt region
751 0 BONDPAD.L.1: Bondpad length must be >= 68.0 um
755 0 NBL.X.1: Nburied must have an Nwell isolation ring
759 0 NHVT.X.1: Nhvt to Oxide enclosure must be == 0.0 on all sides
763 0 PHVT.X.1: Phvt to Oxide enclosure must be == 0.0 on all sides
768 0 BONDPAD.O.1: Bondpads must contain Metal 1
775 0 BONDPAD.O.1: Bondpads must contain Metal 2
785 0 BONDPAD.O.1: Bondpads must contain Metal 3
792 0 BONDPAD.O.1: Bondpads must contain Metal 4
799 0 BONDPAD.O.1: Bondpads must contain Metal 5
806 0 BONDPAD.O.1: Bondpads must contain Metal 6
813 0 BONDPAD.O.1: Bondpads must contain Metal 7
820 0 BONDPAD.O.1: Bondpads must contain Metal 8
828 0 BONDPAD.O.1: Bondpads must contain Metal 9
869 0 NZVT.O.1: Nzvt to Oxide enclosure must be == 0.3
1120 0 BONDPAD.O.2: Bondpad Metal1/Metal2 intersection must contain Via 1
1125 0 BONDPAD.O.2: Bondpad Metal2/Metal3 intersection must contain Via 2
1130 0 BONDPAD.O.2: Bondpad Metal3/Metal4 intersection must contain Via 3
1135 0 BONDPAD.O.2: Bondpad Metal4/Metal5 intersection must contain Via 4
1140 0 BONDPAD.O.2: Bondpad Metal5/Metal6 intersection must contain Via 5
1145 0 BONDPAD.O.2: Bondpad Metal6/Metal7 intersection must contain Via 6
1150 0 BONDPAD.O.2: Bondpad Metal7/Metal8 intersection must contain Via 7
1155 0 BONDPAD.O.2: Bondpad Metal8/Metal9 intersection must contain Via 8
1551 0 POLY.SE.3: Poly width, between two contacts spaced > 25.0um, must be >= 0.14um
1563 0 BONDPAD.SP.5: Bondpad Metal1 slot to Bondpad Metal1 slot spacing must be == 1.50
1567 0 BONDPAD.W.4: Bondpad Metal1 slot width must be == 1.00
1578 0 BONDPAD.R.1: Minimum Bondpad Via1 inside Metal1 to Metal2 crossing must be >= 16.0
1583 0 BONDPAD.SP.5: Bondpad Metal2 slot to Bondpad Metal2 slot spacing must be == 1.50
1587 0 BONDPAD.W.4: Bondpad Metal2 slot width must be == 1.00
1598 0 BONDPAD.R.1: Minimum Bondpad Via2 inside Metal2 to Metal3 crossing must be >= 16.0
1603 0 BONDPAD.SP.5: Bondpad Metal3 slot to Bondpad Metal3 slot spacing must be == 1.50
1607 0 BONDPAD.W.4: Bondpad Metal3 slot width must be == 1.00
1618 0 BONDPAD.R.1: Minimum Bondpad Via3 inside Metal3 to Metal4 crossing must be >= 16.0
1623 0 BONDPAD.SP.5: Bondpad Metal4 slot to Bondpad Metal4 slot spacing must be == 1.50
1627 0 BONDPAD.W.4: Bondpad Metal4 slot width must be == 1.00
1638 0 BONDPAD.R.1: Minimum Bondpad Via4 inside Metal4 to Metal5 crossing must be >= 16.0
1643 0 BONDPAD.SP.5: Bondpad Metal5 slot to Bondpad Metal5 slot spacing must be == 1.50
1647 0 BONDPAD.W.4: Bondpad Metal5 slot width must be == 1.00
1658 0 BONDPAD.R.1: Minimum Bondpad Via5 inside Metal5 to Metal6 crossing must be >= 16.0
1663 0 BONDPAD.SP.5: Bondpad Metal6 slot to Bondpad Metal6 slot spacing must be == 1.50
1667 0 BONDPAD.W.4: Bondpad Metal6 slot width must be == 1.00
1678 0 BONDPAD.R.1: Minimum Bondpad Via6 inside Metal6 to Metal7 crossing must be >= 16.0
1683 0 BONDPAD.SP.5: Bondpad Metal7 slot to Bondpad Metal7 slot spacing must be == 1.50
1687 0 BONDPAD.W.4: Bondpad Metal7 slot width must be == 1.00
1698 0 BONDPAD.R.2: Minimum Bondpad Via7 inside Metal7 to Metal8 crossing must be >= 4.0
1703 0 BONDPAD.SP.5: Bondpad Metal8 slot to Bondpad Metal8 slot spacing must be == 1.50
1707 0 BONDPAD.W.4: Bondpad Metal8 slot width must be == 1.00
1712 0 BONDPAD.R.2: Minimum Bondpad Via8 inside Metal8 to Metal9 crossing must be >= 4.0
2393 0 OXIDE.L.1_OXIDE.L.2: Maximum Oxide length between two contacts (when the Oxide width is <= 0.18um) must be <= 22.0um and Maximum Oxide length between one contact and the end of the Oxide line (when the Oxide width is <= 0.18um) must be <= 11.0um
2421 0 BONDPAD.W.5: Bondpad Metal1 outside Metal1 ring width must be == 5.00
2449 0 BONDPAD.W.5: Bondpad Metal2 outside Metal2 ring width must be == 5.00
2477 0 BONDPAD.W.5: Bondpad Metal3 outside Metal3 ring width must be == 5.00
2505 0 BONDPAD.W.5: Bondpad Metal4 outside Metal4 ring width must be == 5.00
2533 0 BONDPAD.W.5: Bondpad Metal5 outside Metal5 ring width must be == 5.00
2561 0 BONDPAD.W.5: Bondpad Metal6 outside Metal6 ring width must be == 5.00
2589 0 BONDPAD.W.5: Bondpad Metal7 outside Metal7 ring width must be == 5.00
2617 0 BONDPAD.W.5: Bondpad Metal8 outside Metal8 ring width must be == 5.00
2637 0 VIA1.X.2: Metal1 must connect to Metal2 with >= 4 Via1 spaced < 0.30 um or >= 9 Via1 spaced < 0.60 um
2656 0 VIA2.X.2: Metal2 must connect to Metal3 with >= 4 Via2 spaced < 0.30 um or >= 9 Via2 spaced < 0.60 um
2676 0 VIA3.X.2: Metal3 must connect to Metal4 with >= 4 Via3 spaced < 0.30 um or >= 9 Via3 spaced < 0.60 um
2696 0 VIA4.X.2: Metal4 must connect to Metal5 with >= 4 Via4 spaced < 0.30 um or >= 9 Via4 spaced < 0.60 um
2716 0 VIA5.X.2: Metal5 must connect to Metal6 with >= 4 Via5 spaced < 0.30 um or >= 9 Via5 spaced < 0.60 um
2736 0 VIA6.X.2: Metal6 must connect to Metal7 with >= 4 Via6 spaced < 0.30 um or >= 9 Via6 spaced < 0.60 um
2756 0 VIA1.X.1: Metal1 must connect to Metal2 with >= 2 Via1 spaced < 0.30 um or >= 4 Via1 spaced < 0.60 um
2776 0 VIA2.X.1: Metal2 must connect to Metal3 with >= 2 Via2 spaced < 0.30 um or >= 4 Via2 spaced < 0.60 um
2796 0 VIA3.X.1: Metal3 must connect to Metal4 with >= 2 Via3 spaced < 0.30 um or >= 4 Via3 spaced < 0.60 um
2816 0 VIA4.X.1: Metal4 must connect to Metal5 with >= 2 Via4 spaced < 0.30 um or >= 4 Via4 spaced < 0.60 um
2836 0 VIA5.X.1: Metal5 must connect to Metal6 with >= 2 Via5 spaced < 0.30 um or >= 4 Via5 spaced < 0.60 um
2856 0 VIA6.X.1: Metal6 must connect to Metal7 with >= 2 Via6 spaced < 0.30 um or >= 4 Via6 spaced < 0.60 um
2862 0 BONDPAD.B.1: Bondpad Metal1 must have bevelled corners
2868 0 BONDPAD.B.1: Bondpad Metal2 must have bevelled corners
2874 0 BONDPAD.B.1: Bondpad Metal3 must have bevelled corners
2880 0 BONDPAD.B.1: Bondpad Metal4 must have bevelled corners
2886 0 BONDPAD.B.1: Bondpad Metal5 must have bevelled corners
2892 0 BONDPAD.B.1: Bondpad Metal6 must have bevelled corners
2898 0 BONDPAD.B.1: Bondpad Metal7 must have bevelled corners
2904 0 BONDPAD.B.1: Bondpad Metal8 must have bevelled corners
2910 0 BONDPAD.B.1: Bondpad Metal9 must have bevelled corners
2912 0 ptap_StampErrorFloat
2913 0 ptap_StampErrorMult
2914 0 ptap_StampErrorConnect
2919 0 psubstrate_StampErrorFloat
2920 0 psubstrate_StampErrorMult
2921 0 psubstrate_StampErrorConnect
2926 0 ntap_StampErrorFloat
2927 0 ntap_StampErrorMult
2928 0 ntap_StampErrorConnect
2933 0 nwell_conn_StampErrorFloat
2934 0 nwell_conn_StampErrorMult
2935 0 nwell_conn_StampErrorConnect
2940 0 nb_tap_StampErrorFloat
2941 0 nb_tap_StampErrorMult
2942 0 nb_tap_StampErrorConnect
2947 0 Nburied_StampErrorFloat
2948 0 Nburied_StampErrorMult
2949 0 Nburied_StampErrorConnect
2987 0 NBL.W.1: Nburied width must be >= 3.2 um
2989 0 NBL.E.1: Nburied to Nwell enclosure must be >= 0.4 um
2991 0 NBL.SP.1: Nburied to Nburied spacing must be >= 5.0 um
2994 0 NBL.SE.2: Nburied to Oxide spacing must be >= 2.2 um
2995 0 NBL.SE.2: Nburied to Oxide spacing must be >= 2.2 um
2996 0 NBL.SE.1: Nburied to non-related Nwell spacing must be >= 4.4 um
3001 0 NBL.SE.3: Nwell ring (on Nburied) to P+ Oxide spacing must be >= 0.5 um
3003 0 NBL.SE.3: Nwell ring (on Nburied) to P+ Oxide spacing must be >= 0.5 um
3007 0 NBL.SE.4: Nwell ring (on Nburied) to N+ Oxide spacing must be >= 0.4 um
3009 0 NBL.SE.4: Nwell ring (on Nburied) to N+ Oxide spacing must be >= 0.4 um
3011 0 NW.SP.1: Nwell to Nwell spacing (same potential) must be >= 0.6 um
3013 0 NW.SP.1: Nwell to Nwell spacing (same potential) must be >= 0.6 um
3016 0 NW.SP.2: Nwell to Nwell spacing (diferent potential) must be >= 1.2 um
3017 0 NW.SP.2: Nwell to Nwell spacing (diferent potential) must be >= 1.2 um
3019 0 NW.SP.2: Nwell to Nwell spacing (diferent potential) must be >= 1.2 um
3020 0 NW.W.1: Nwell width must be >= 0.6 um
3024 0 NW.SP.2: Nwell to Nwell spacing (diferent potential) must be >= 1.2 um
3025 0 NW.SE.1: Nwell to Oxide spacing must be >= 0.3 um
3028 0 NW.SE.2: Nwell to P+ Oxide spacing must be >= 0.3 um
3029 0 NW.SE.2: Nwell to P+ Oxide spacing must be >= 0.3 um
3034 0 NW.SE.3: Nwell to N+ 2.5V Oxide spacing must be >= 0.5 um
3035 0 NW.SE.3: Nwell to N+ 2.5V Oxide spacing must be >= 0.5 um
3040 0 NW.SE.4: Nwell to P+ 2.5V Oxide spacing must be >= 0.5 um
3041 0 NW.SE.4: Nwell to P+ 2.5V Oxide spacing must be >= 0.5 um
3046 0 NW.E.1: Nwell to N+ Oxide enclosure must be >= 0.12 um
3047 0 NW.E.2: Nwell to P+ Oxide enclosure must be >= 0.12 um
3049 0 NW.E.2: Nwell to P+ Oxide enclosure must be >= 0.12 um
3050 0 NW.E.3: Nwell to N+ 2.5V Oxide enclosure must be >= 0.7 um
3052 0 NW.E.3: Nwell to N+ 2.5V Oxide enclosure must be >= 0.7 um
3053 0 NW.E.4: Nwell to P+ 2.5V Oxide enclosure must be >= 0.7 um
3055 0 NW.E.4: Nwell to P+ 2.5V Oxide enclosure must be >= 0.7 um
3056 0 NWR.SE.1: Nwell (in resistor) to SiProt spacing must be >= 0.32 um
3058 0 NWR.E.1: Oxide to Nwell (in resistor) enclosure must be >= 1.2 um
3060 0 NWR.E.1: Oxide to Nwell (in resistor) enclosure must be >= 1.2 um
3062 0 NWR.E.2: Nwell (in resistor) to Cont enclosure must be >= 0.32 um
3064 0 NWR.E.2: Nwell (in resistor) to Cont enclosure must be >= 0.32 um
3065 0 NWR.O.1: SiProt to Nimp overlap must be >= 0.45 um
3066 0 NWR.X.1: Thick Oxide is NOT allowed over Nwell resistor
3067 0 OXIDE.W.1: Oxide width must be >= 0.1 um
3072 0 OXIDE.W.2.1.1: 1.2V N-channel gate width must be >= 0.12 um
3076 0 OXIDE.W.2.1.2: 2.5V N-channel gate width must be >= 0.15 um
3081 0 OXIDE.W.2.2.1: 1.2V P-channel gate width must be >= 0.12 um
3085 0 OXIDE.W.2.2.2: 2.5V P-channel gate width must be >= 0.15 um
3087 0 OXIDE.W.3: Oxide (45 degree) width must be >= 0.13 um
3089 0 OXIDE.SP.1: N+ Oxide to N+ Oxide spacing must be >= 0.15 um
3091 0 OXIDE.SP.2: P+ Oxide to P+ Oxide spacing must be >= 0.15 um
3096 0 OXIDE.SP.3: P+ Oxide to P+ Oxide spacing must be >= 0.15 um
3097 0 OXIDE.SE.1: Oxide to Oxide_thk spacing must be >= 0.28 um
3098 0 OXIDE.SP.4: Oxide bent 45 degree to Oxide spacing must be >= 0.18 um
3099 0 OXIDE.A.1: Oxide area must be >= 0.06 um
3103 0 OXIDE.EA.1: Oxide enclosed area must be >= 0.10 um
3107 0 OXIDE.X.1: Oxide must be covered by Nimp or Pimp or Nzvt
3110 0 OXIDER.SE.2: Oxide resistor to Nimp spacing must be >= 0.3 um
3111 0 OXIDER.SE.2: Oxide resistor to Nimp spacing must be >= 0.3 um
3114 0 OXIDER.SE.2: Oxide resistor to Pimp spacing must be >= 0.3 um
3115 0 OXIDER.SE.2: Oxide resistor to Pimp spacing must be >= 0.3 um
3117 0 OXIDER.E.1: SiProt to Oxide resistor enclosure must be >= 0.25 um
3119 0 OXIDER.X.1: Oxide resistors must have N+ or P+ Implant
3120 0 OXIDETHK.W.1: Oxide_thk width must be >= 0.7 um
3122 0 OXIDETHK.SP.1: Oxide_thk to Oxide_thk spacing must be >= 0.35 um
3124 0 OXIDETHK.SP.2: Oxide_thk (bent 45 degree) to Oxide_thk spacing must be >= 0.75 um
3126 0 OXIDETHK.SE.1: 2.5V N+ Oxide to 2.5V N+ Oxide spacing must be >= 0.20 um
3128 0 OXIDETHK.SE.2: 2.5V P+ Oxide to 2.5V P+ Oxide spacing must be >= 0.20 um
3133 0 OXIDETHK.SE.3: 2.5V N+ Oxide to 2.5V P+ Oxide spacing must be >= 0.25 um
3135 0 OXIDETHK.E.1: Oxide_thk to Oxide enclosure must be >= 0.30 um
3142 0 OXIDETHK.SE.5: Oxide_thk to Poly gate spacing must be >= 0.34 um
3143 0 OXIDETHK.SE.5: Oxide_thk to Poly gate spacing must be >= 0.34 um
3145 0 OXIDETHK.E.2: Oxide_thk to Poly gate enclosure must be >= 0.36 um
3146 0 NHVT.X.2: Nhvt is NOT allowed on Nwell
3147 0 NHVT.X.3: Nhvt is NOT allowed on P+ Oxide
3148 0 NHVT.X.4: Nhvt is NOT allowed on Nzvt
3149 0 PHVT.X.2: Phvt is NOT allowed outside Nwell
3150 0 PHVT.X.3: Phvt is NOT allowed on N+ Oxide
3151 0 PHVT.X.4: Phvt is NOT allowed on Nzvt
3152 0 NZVT.W.1: Nzvt width must be >= 0.7 um
3154 0 NZVT.SP.1: Nzvt to Nzvt spacing must be >= 0.6 um
3157 0 NZVT.SE.1: Nzvt to Oxide spacing must be >= 0.28 um
3158 0 NZVT.SE.1: Nzvt to Oxide spacing must be >= 0.28 um
3159 0 NZVT.SE.2: Nzvt to Nwell spacing must be >= 1.2 um
3160 0 NZVT.SE.2: Nzvt to Nwell spacing must be >= 1.2 um
3163 0 NZVT.E.1: Poly to Oxide enclosure must be >= 0.2 um
3166 0 NZVT.L.1: Native Device Poly gate length must be >= 0.9 um
3170 0 NZVT.W.2: Native Device Poly gate width must be >= 0.65 um
3172 0 NZVT.X.3: P+ Oxide is NOT allowed in Nzvt
3175 0 POLY.W.1: 1.2V N+ Poly gate length must be >= 0.1 um
3178 0 POLY.W.2: 1.2V P+ Poly gate length must be >= 0.1 um
3182 0 POLY.W.3: 2.5V N+ Poly gate length must be >= 0.28 um
3187 0 POLY.W.4: 2.5V P+ Poly gate length must be >= 0.28 um
3190 0 POLY.W.5: Poly interconnect width must be >= 0.1 um
3194 0 POLY.SP.1: Poly resistor to Poly resistor spacing must be >= 0.6 um
3196 0 POLY.SP.2: Poly gate to Poly gate spacing must be >= 0.12 um
3198 0 POLY.SP.3: Poly interconnect to Poly interconnect spacing must be >= 0.12 um
3200 0 POLY.E.1: Poly to N+ Oxide enclosure must be >= 0.18 um
3202 0 POLY.E.2: Poly to P+ Oxide enclosure must be >= 0.18 um
3203 0 POLY.SE.1_POLY.SE.2: Poly to Oxide spacing must be >= 0.1 um
3205 0 POLY.E.3: Oxide to Poly enclosure must be >= 0.2 um
3207 0 POLY.W.6: Bent Poly width must be >= 0.18 um
3209 0 POLY.SP.4: Bent Poly to bent Poly spacing must be >= 0.22 um
3210 0 POLY.X.1: Poly gate cannot have bends
3211 0 POLY.X.2: Poly resistor cannot have bends
3212 0 POLY.A.1: Poly area must be >= 0.1 um
3214 0 POLYR.E.1: SiProt to Poly resistor enclosure must be >= 0.28 um
3216 0 POLYR.E.2: Nimp to Poly used in resistor enclosure must be >= 0.15 um
3218 0 POLYR.E.2: Nimp to Poly used in resistor enclosure must be >= 0.15 um
3220 0 POLYR.E.3: Pimp to Poly used in resistor enclosure must be >= 0.15 um
3222 0 POLYR.E.3: Pimp to Poly used in resistor enclosure must be >= 0.15 um
3224 0 POLYR.SE.2: Poly resistor to Nimp spacing must be >= 0.3 um
3225 0 POLYR.SE.2: Poly resistor to Nimp spacing must be >= 0.3 um
3226 0 POLYR.SE.2: Poly resistor to Nzvt spacing must be >= 0.3 um
3227 0 POLYR.SE.2: Poly resistor to Nzvt spacing must be >= 0.3 um
3229 0 POLYR.SE.2: Poly resistor to Pimp spacing must be >= 0.3 um
3230 0 POLYR.SE.2: Poly resistor to Pimp spacing must be >= 0.3 um
3231 0 POLYR.X.1: Poly resistors must have N+ or P+ Implant
3232 0 NIMP.W.1: Nimp width must be >= 0.24 um
3234 0 NIMP.SP.1: Nimp to Nimp spacing must be >= 0.24 um
3237 0 NIMP.E.1: Nimp to Oxide enclosure must be >= 0.14 um
3238 0 NIMP.O.1: Nimp to Oxide overlap must be >= 0.16 um
3246 0 NIMP.SE.1: Nimp to P+ Oxide spacing must be >= 0.16 um
3247 0 NIMP.SE.1: Nimp to P+ Oxide spacing must be >= 0.16 um
3250 0 NIMP.E.2: Nimp to Oxide (Nwell tie) enclosure must be >= 0.02 um
3254 0 NIMP.E.3: Nimp to Poly gate enclosure must be >= 0.18 um
3260 0 NIMP.E.4: Nimp to gate end enclosure must be >= 0.18 um
3262 0 NIMP.E.4: Nimp to gate end enclosure must be >= 0.18 um
3271 0 NIMP.SE.2: Nimp to P+ Oxide spacing must be >= 0.02 um
3272 0 NIMP.SE.2: Nimp to P+ Oxide spacing must be >= 0.02 um
3273 0 NIMP.A.1: Nimp area must be >= 0.15 um
3277 0 NIMP.EA.1: Area in Nimp ring must be >= 0.16 um
3280 0 NIMP.SE.3: Nimp to P+ gate spacing must be >= 0.18 um
3281 0 NIMP.SE.3: Nimp to P+ gate spacing must be >= 0.18 um
3282 0 NIMP.X.1: Nimp is NOT allowed over Pimp
3283 0 PIMP.W.1: Pimp width must be >= 0.24 um
3285 0 PIMP.SP.1: Pimp to Pimp spacing must be >= 0.24 um
3287 0 PIMP.E.1: Pimp to Oxide enclosure must be >= 0.14 um
3288 0 PIMP.O.1: Pimp to Oxide overlap must be >= 0.16 um
3296 0 PIMP.SE.1: Pimp to N+ Oxide spacing must be >= 0.16 um
3297 0 PIMP.SE.1: Pimp to N+ Oxide spacing must be >= 0.16 um
3299 0 PIMP.E.2: Pimp to Oxide (substrate tie) enclosure must be >= 0.02 um
3303 0 PIMP.E.3: Pimp to Poly gate enclosure must be >= 0.18 um
3306 0 PIMP.E.4: Pimp to gate end enclosure must be >= 0.18 um
3308 0 PIMP.E.4: Pimp to gate end enclosure must be >= 0.18 um
3317 0 PIMP.SE.2: Pimp to N+ Oxide spacing must be >= 0.02 um
3318 0 PIMP.SE.2: Pimp to N+ Oxide spacing must be >= 0.02 um
3319 0 PIMP.A.1: Pimp area must be >= 0.15 um
3323 0 PIMP.EA.1: Area in Pimp ring must be >= 0.16 um
3326 0 PIMP.SE.3: Pimp to N+ gate spacing must be >= 0.18 um
3327 0 PIMP.SE.3: Pimp to N+ gate spacing must be >= 0.18 um
3329 0 CONT.W.1: Cont shapes must be 0.12x0.12 rectangles
3331 0 CONT.SP.1: Cont to Cont spacing must be >= 0.14 um
3334 0 CONT.SP.2: Cont to Cont (in array) spacing must be >= 0.16 um
3337 0 CONT.SE.1: Cont to gate spacing must be >= 0.10 um
3338 0 CONT.SE.1: Cont to gate spacing must be >= 0.10 um
3344 0 CONT.SE.2: Cont to 2.5V gate spacing must be >= 0.12 um
3345 0 CONT.SE.2: Cont to 2.5V gate spacing must be >= 0.12 um
3347 0 CONT.SE.3: Poly Cont to Oxide spacing must be >= 0.12 um
3348 0 CONT.SE.3: Poly Cont to Oxide spacing must be >= 0.12 um
3353 0 CONT.SE.4: Poly Cont to Oxide spacing must be >= 0.14 um
3354 0 CONT.SE.4: Poly Cont to Oxide spacing must be >= 0.14 um
3356 0 CONT.E.1: Oxide to Cont enclosure must be >= 0.06 um
3358 0 CONT.E.1: Oxide to Cont enclosure must be >= 0.06 um
3360 0 CONT.E.2: Poly to Cont enclosure must be >= 0.04 um
3362 0 CONT.E.2: Poly to Cont enclosure must be >= 0.04 um
3365 0 CONT.E.3: Poly to Cont enclosure on at least two opposite sides must be >= 0.06 um
3367 0 CONT.E.4: Nimp to Cont enclosure must be >= 0.06 um
3369 0 CONT.E.4: Nimp to Cont enclosure must be >= 0.06 um
3371 0 CONT.E.4: Pimp to Cont enclosure must be >= 0.06 um
3373 0 CONT.E.4: Pimp to Cont enclosure must be >= 0.06 um
3375 0 CONT.X.1: Cont on gate is NOT allowed
3378 0 CONT.X.2: Nimp edge is NOT allowed on Oxide Cont
3381 0 CONT.X.2: Pimp edge is NOT allowed on Oxide Cont
3382 0 CONT.X.3: Cont must be covered by Oxide or Poly
3383 0 SIPROT.W.1: SiProt width must be >= 0.44 um
3385 0 SIPROT.SP.1: SiProt to SiProt spacing must be >= 0.44 um
3388 0 SIPROT.SE.1: SiProt to Cont spacing must be >= 0.24 um
3389 0 SIPROT.SE.1: SiProt to Cont spacing must be >= 0.24 um
3390 0 SIPROT.SE.2: SiProt to Oxide spacing must be >= 0.24 um
3394 0 SIPROT.SE.3: SiProt to Poly gate spacing must be >= 0.44 um
3395 0 SIPROT.SE.3: SiProt to Poly gate spacing must be >= 0.44 um
3397 0 SIPROT.E.2: Oxide to SiProt enclosure must be >= 0.24 um
3401 0 SIPROT.E.1: SiProt to Oxide enclosure must be >= 0.25 um
3403 0 SIPROT.E.3: SiProt to Poly enclosure must be >= 0.28 um
3404 0 SIPROT.A.1: SiProt area must be >= 1.2 um
3405 0 SIPROT.SE.4: SiProt to Poly (on field) spacing must be >= 0.35 um
3409 0 SIPROT.EA.1: Area in SiProt ring must be >= 1.2 um
3410 0 METAL2.E.1: Metal2 to Via1 enclosure must be >= 0.005 um
3412 0 METAL2.E.1: Metal2 to Via1 enclosure must be >= 0.005 um
3416 0 METAL2.E.2: Metal2 to Via1 enclosure on opposite sides must be >= 0.06 um
3417 0 METAL3.E.1: Metal3 to Via2 enclosure must be >= 0.005 um
3419 0 METAL3.E.1: Metal3 to Via2 enclosure must be >= 0.005 um
3423 0 METAL3.E.2: Metal3 to Via2 enclosure on opposite sides must be >= 0.06 um
3424 0 METAL4.E.1: Metal4 to Via3 enclosure must be >= 0.005 um
3426 0 METAL4.E.1: Metal4 to Via3 enclosure must be >= 0.005 um
3430 0 METAL4.E.2: Metal4 to Via3 enclosure on opposite sides must be >= 0.06 um
3431 0 METAL5.E.1: Metal5 to Via4 enclosure must be >= 0.005 um
3433 0 METAL5.E.1: Metal5 to Via4 enclosure must be >= 0.005 um
3437 0 METAL5.E.2: Metal5 to Via4 enclosure on opposite sides must be >= 0.06 um
3438 0 METAL6.E.1: Metal6 to Via5 enclosure must be >= 0.005 um
3440 0 METAL6.E.1: Metal6 to Via5 enclosure must be >= 0.005 um
3444 0 METAL6.E.2: Metal6 to Via5 enclosure on opposite sides must be >= 0.06 um
3445 0 METAL7.E.1: Metal7 to Via6 enclosure must be >= 0.005 um
3447 0 METAL7.E.1: Metal7 to Via6 enclosure must be >= 0.005 um
3451 0 METAL7.E.2: Metal7 to Via6 enclosure on opposite sides must be >= 0.06 um
3452 0 METAL8.E.1: Metal8 to Via7 enclosure must be >= 0.05 um
3454 0 METAL8.E.1: Metal8 to Via7 enclosure must be >= 0.05 um
3458 0 METAL8.E.2: Metal8 to Via7 enclosure on opposite sides must be >= 0.1 um
3459 0 METAL9.E.1: Metal9 to Via8 enclosure must be >= 0.05 um
3461 0 METAL9.E.1: Metal9 to Via8 enclosure must be >= 0.05 um
3465 0 METAL9.E.2: Metal9 to Via8 enclosure on opposite sides must be >= 0.1 um
3466 0 METAL1.E.1: Metal1 to Cont enclosure must be >= 0.00 um
3470 0 METAL1.E.2: Metal1 to Cont enclosure on opposite sides must be >= 0.06 um
3471 0 METAL1.W.1: Metal1 width must be >= 0.12 um
3472 0 METAL2.W.1: Metal2 width must be >= 0.14 um
3473 0 METAL3.W.1: Metal3 width must be >= 0.14 um
3474 0 METAL4.W.1: Metal4 width must be >= 0.14 um
3475 0 METAL5.W.1: Metal5 width must be >= 0.14 um
3476 0 METAL6.W.1: Metal6 width must be >= 0.14 um
3477 0 METAL7.W.1: Metal7 width must be >= 0.14 um
3478 0 METAL8.W.1: Metal8 width must be >= 0.44 um
3479 0 METAL9.W.1: Metal9 width must be >= 0.44 um
3483 0 METAL1.W.2: Metal1 width must be <= 12.0 um
3487 0 METAL2.W.2: Metal2 width must be <= 12.0 um
3491 0 METAL3.W.2: Metal3 width must be <= 12.0 um
3495 0 METAL4.W.2: Metal4 width must be <= 12.0 um
3499 0 METAL5.W.2: Metal5 width must be <= 12.0 um
3503 0 METAL6.W.2: Metal6 width must be <= 12.0 um
3506 0 METAL7.W.2: Metal7 width must be <= 12.0 um
3508 0 METAL8.W.2: Metal8 width must be <= 12.0 um
3510 0 METAL9.W.2: Metal9 width must be <= 12.0 um
3512 0 METAL1.SP.1.1: Metal1 to Metal1 spacing must be >= 0.12 um
3514 0 METAL2.SP.1.1: Metal2 to Metal2 spacing must be >= 0.14 um
3516 0 METAL3.SP.1.1: Metal3 to Metal3 spacing must be >= 0.14 um
3518 0 METAL4.SP.1.1: Metal4 to Metal4 spacing must be >= 0.14 um
3520 0 METAL5.SP.1.1: Metal5 to Metal5 spacing must be >= 0.14 um
3522 0 METAL6.SP.1.1: Metal6 to Metal6 spacing must be >= 0.14 um
3524 0 METAL7.SP.1.1: Metal7 to Metal7 spacing must be >= 0.14 um
3526 0 METAL8.SP.1.1: Metal8 to Metal8 spacing must be >= 0.40 um
3528 0 METAL9.SP.1.1: Metal9 to Metal9 spacing must be >= 0.40 um
3535 0 METAL1.SP.1.2: Metal1 to Metal1 spacing must be >= 0.18 um
3542 0 METAL2.SP.1.2: Metal2 to Metal2 spacing must be >= 0.20 um
3549 0 METAL3.SP.1.2: Metal3 to Metal3 spacing must be >= 0.20 um
3556 0 METAL4.SP.1.2: Metal4 to Metal4 spacing must be >= 0.20 um
3563 0 METAL5.SP.1.2: Metal5 to Metal5 spacing must be >= 0.20 um
3570 0 METAL6.SP.1.2: Metal6 to Metal6 spacing must be >= 0.20 um
3577 0 METAL7.SP.1.2: Metal7 to Metal7 spacing must be >= 0.20 um
3584 0 METAL1.SP.1.3: Metal1 to Metal1 spacing must be >= 0.50 um
3591 0 METAL2.SP.1.3: Metal2 to Metal2 spacing must be >= 0.50 um
3598 0 METAL3.SP.1.3: Metal3 to Metal3 spacing must be >= 0.50 um
3605 0 METAL4.SP.1.3: Metal4 to Metal4 spacing must be >= 0.50 um
3612 0 METAL5.SP.1.3: Metal5 to Metal5 spacing must be >= 0.50 um
3619 0 METAL6.SP.1.3: Metal6 to Metal6 spacing must be >= 0.50 um
3626 0 METAL7.SP.1.3: Metal7 to Metal7 spacing must be >= 0.50 um
3633 0 METAL8.SP.1.2: Metal8 to Metal8 spacing must be >= 0.50 um
3640 0 METAL9.SP.1.2: Metal9 to Metal9 spacing must be >= 0.50 um
3647 0 METAL1.SP.1.4: Metal1 to Metal1 spacing must be >= 0.90 um
3654 0 METAL2.SP.1.4: Metal2 to Metal2 spacing must be >= 0.90 um
3661 0 METAL3.SP.1.4: Metal3 to Metal3 spacing must be >= 0.90 um
3668 0 METAL4.SP.1.4: Metal4 to Metal4 spacing must be >= 0.90 um
3675 0 METAL5.SP.1.4: Metal5 to Metal5 spacing must be >= 0.90 um
3682 0 METAL6.SP.1.4: Metal6 to Metal6 spacing must be >= 0.90 um
3689 0 METAL7.SP.1.4: Metal7 to Metal7 spacing must be >= 0.90 um
3696 0 METAL8.SP.1.3: Metal8 to Metal8 spacing must be >= 0.90 um
3703 0 METAL9.SP.1.3: Metal9 to Metal9 spacing must be >= 0.90 um
3710 0 METAL1.SP.1.5: Metal1 to Metal1 spacing must be >= 1.50 um
3717 0 METAL2.SP.1.5: Metal2 to Metal2 spacing must be >= 1.50 um
3724 0 METAL3.SP.1.5: Metal3 to Metal3 spacing must be >= 1.50 um
3731 0 METAL4.SP.1.5: Metal4 to Metal4 spacing must be >= 1.50 um
3738 0 METAL5.SP.1.5: Metal5 to Metal5 spacing must be >= 1.50 um
3745 0 METAL6.SP.1.5: Metal6 to Metal6 spacing must be >= 1.50 um
3752 0 METAL7.SP.1.5: Metal7 to Metal7 spacing must be >= 1.50 um
3759 0 METAL8.SP.1.4: Metal8 to Metal8 spacing must be >= 1.50 um
3766 0 METAL9.SP.1.4: Metal9 to Metal9 spacing must be >= 1.50 um
3771 0 METAL1.SP.1.6: Metal1 to Metal1 spacing must be >= 2.50 um
3776 0 METAL2.SP.1.6: Metal2 to Metal2 spacing must be >= 2.50 um
3781 0 METAL3.SP.1.6: Metal3 to Metal3 spacing must be >= 2.50 um
3786 0 METAL4.SP.1.6: Metal4 to Metal4 spacing must be >= 2.50 um
3791 0 METAL5.SP.1.6: Metal5 to Metal5 spacing must be >= 2.50 um
3796 0 METAL6.SP.1.6: Metal6 to Metal6 spacing must be >= 2.50 um
3801 0 METAL7.SP.1.6: Metal7 to Metal7 spacing must be >= 2.50 um
3806 0 METAL8.SP.1.5: Metal8 to Metal8 spacing must be >= 2.50 um
3811 0 METAL9.SP.1.5: Metal9 to Metal9 spacing must be >= 2.50 um
3813 0 METAL1.L.1: Metal1 non-90 degree segments must be >= 0.18 um
3815 0 METAL2.L.1: Metal2 non-90 degree segments must be >= 0.20 um
3817 0 METAL3.L.1: Metal3 non-90 degree segments must be >= 0.20 um
3819 0 METAL4.L.1: Metal4 non-90 degree segments must be >= 0.20 um
3821 0 METAL5.L.1: Metal5 non-90 degree segments must be >= 0.20 um
3823 0 METAL6.L.1: Metal6 non-90 degree segments must be >= 0.20 um
3825 0 METAL7.L.1: Metal7 non-90 degree segments must be >= 0.20 um
3826 0 METAL1.SP.2: Metal1 to bent Metal1 spacing must be >= 0.16 um
3827 0 METAL1.W.3: Bent Metal1 (45 degree angle) width must be >= 0.14
3828 0 METAL2.SP.2: Metal2 to bent Metal2 spacing must be >= 0.18 um
3829 0 METAL2.W.3: Bent Metal2 (45 degree angle) width must be >= 0.16
3830 0 METAL3.SP.2: Metal3 to bent Metal3 spacing must be >= 0.18 um
3831 0 METAL3.W.3: Bent Metal3 (45 degree angle) width must be >= 0.16
3832 0 METAL4.SP.2: Metal4 to bent Metal4 spacing must be >= 0.18 um
3833 0 METAL4.W.3: Bent Metal4 (45 degree angle) width must be >= 0.16
3834 0 METAL5.SP.2: Metal5 to bent Metal5 spacing must be >= 0.18 um
3835 0 METAL5.W.3: Bent Metal5 (45 degree angle) width must be >= 0.16
3836 0 METAL6.SP.2: Metal6 to bent Metal6 spacing must be >= 0.18 um
3837 0 METAL6.W.3: Bent Metal6 (45 degree angle) width must be >= 0.16
3838 0 METAL7.SP.2: Metal7 to bent Metal7 spacing must be >= 0.18 um
3839 0 METAL7.W.3: Bent Metal7 (45 degree angle) width must be >= 0.16
3840 0 METAL1.A.1: Metal1 area must be >= 0.07 um
3841 0 METAL2.A.1: Metal2 area must be >= 0.08 um
3842 0 METAL3.A.1: Metal3 area must be >= 0.08 um
3843 0 METAL4.A.1: Metal4 area must be >= 0.08 um
3844 0 METAL5.A.1: Metal5 area must be >= 0.08 um
3845 0 METAL6.A.1: Metal6 area must be >= 0.08 um
3846 0 METAL7.A.1: Metal7 area must be >= 0.08 um
3847 0 METAL8.A.1: Metal8 area must be >= 0.2 um
3848 0 METAL9.A.1: Metal9 area must be >= 0.2 um
3850 0 VIA1.W.1: Via1 shapes must be 0.14x0.14 rectangles
3852 0 VIA1.SP.1: Via1 to Via1 spacing must be >= 0.15 um
3864 0 VIA1.SP.2: Via1 to Via1 spacing must be >= 0.20 um
3866 0 VIA2.W.1: Via2 shapes must be 0.14x0.14 rectangles
3868 0 VIA2.SP.1: Via2 to Via2 spacing must be >= 0.15 um
3880 0 VIA2.SP.2: Via2 to Via2 spacing must be >= 0.20 um
3882 0 VIA3.W.1: Via3 shapes must be 0.14x0.14 rectangles
3884 0 VIA3.SP.1: Via3 to Via3 spacing must be >= 0.15 um
3896 0 VIA3.SP.2: Via3 to Via3 spacing must be >= 0.20 um
3898 0 VIA4.W.1: Via4 shapes must be 0.14x0.14 rectangles
3900 0 VIA4.SP.1: Via4 to Via4 spacing must be >= 0.15 um
3912 0 VIA4.SP.2: Via4 to Via4 spacing must be >= 0.20 um
3914 0 VIA5.W.1: Via5 shapes must be 0.14x0.14 rectangles
3916 0 VIA5.SP.1: Via5 to Via5 spacing must be >= 0.15 um
3928 0 VIA5.SP.2: Via5 to Via5 spacing must be >= 0.20 um
3930 0 VIA6.W.1: Via6 shapes must be 0.14x0.14 rectangles
3932 0 VIA6.SP.1: Via6 to Via6 spacing must be >= 0.15 um
3944 0 VIA6.SP.2: Via6 to Via6 spacing must be >= 0.20 um
3946 0 VIA7.W.1: Via7 shapes must be 0.36x0.36 rectangles
3948 0 VIA7.SP.1: Via7 to Via7 spacing must be >= 0.36 um
3950 0 VIA8.W.1: Via8 shapes must be 0.36x0.36 rectangles
3952 0 VIA8.SP.1: Via8 to Via8 spacing must be >= 0.36 um
3953 0 VIA1.E.1: Metal1 to Via1 enclosure must be >= 0.005 um
3955 0 VIA1.E.1: Metal1 to Via1 enclosure must be >= 0.005 um
3959 0 VIA1.E.2: Metal1 to Via1 enclosure on opposite sides must be >= 0.06 um
3960 0 VIA2.E.1: Metal2 to Via2 enclosure must be >= 0.005 um
3962 0 VIA2.E.1: Metal2 to Via2 enclosure must be >= 0.005 um
3966 0 VIA2.E.2: Metal2 to Via2 enclosure on opposite sides must be >= 0.06 um
3967 0 VIA3.E.1: Metal3 to Via3 enclosure must be >= 0.005 um
3969 0 VIA3.E.1: Metal3 to Via3 enclosure must be >= 0.005 um
3973 0 VIA3.E.2: Metal3 to Via3 enclosure on opposite sides must be >= 0.06 um
3974 0 VIA4.E.1: Metal4 to Via4 enclosure must be >= 0.005 um
3976 0 VIA4.E.1: Metal4 to Via4 enclosure must be >= 0.005 um
3980 0 VIA4.E.2: Metal4 to Via4 enclosure on opposite sides must be >= 0.06 um
3981 0 VIA5.E.1: Metal5 to Via5 enclosure must be >= 0.005 um
3983 0 VIA5.E.1: Metal5 to Via5 enclosure must be >= 0.005 um
3987 0 VIA5.E.2: Metal5 to Via5 enclosure on opposite sides must be >= 0.06 um
3988 0 VIA6.E.1: Metal6 to Via6 enclosure must be >= 0.005 um
3990 0 VIA6.E.1: Metal6 to Via6 enclosure must be >= 0.005 um
3994 0 VIA6.E.2: Metal6 to Via6 enclosure on opposite sides must be >= 0.06 um
3995 0 VIA7.E.1: Metal7 to Via7 enclosure must be >= 0.03 um
3997 0 VIA7.E.1: Metal7 to Via7 enclosure must be >= 0.03 um
4001 0 VIA7.E.2: Metal7 to Via7 enclosure on opposite sides must be >= 0.08 um
4002 0 VIA8.E.1: Metal8 to Via8 enclosure must be >= 0.03 um
4004 0 VIA8.E.1: Metal8 to Via8 enclosure must be >= 0.03 um
4008 0 VIA8.E.2: Metal8 to Via8 enclosure on opposite sides must be >= 0.08 um
4275 0 LATCHUP.1: P+SD to NW tap spacing must be <= 25.0 um
4656 0 LATCHUP.2: N+SD to Psub tap spacing must be <= 25.0 um
4659 0 LATCHUP.3: NMOS (I/O or ESD) to PMOS (I/O or ESD) spacing must be >= 18.0 um
4660 0 LATCHUP.3: NMOS (I/O or ESD) to PMOS (I/O or ESD) spacing must be >= 18.0 um
4665 0 LATCHUP.3: NMOS (I/O or ESD) to PMOS (I/O or ESD) spacing must be >= 50.0 um when not blocked by a double guard ring
4669 0 LATCHUP.3: NMOS (I/O or ESD) to PMOS (I/O or ESD) spacing must be >= 50.0 um when not blocked by a double guard ring
4671 0 MSLOT1.W.1_MSLOT1.L.1: Metal1 Slot width/length must be >= 2.0 um
4673 0 MSLOT1.SP.1: Metal1 Slot to Metal1 Slot spacing must be >= 0.12 um
4675 0 MSLOT2.W.1_MSLOT2.L.1: Metal2 Slot width/length must be >= 2.0 um
4677 0 MSLOT2.SP.1: Metal2 Slot to Metal2 Slot spacing must be >= 0.14 um
4679 0 MSLOT3.W.1_MSLOT3.L.1: Metal3 Slot width/length must be >= 2.0 um
4681 0 MSLOT3.SP.1: Metal3 Slot to Metal3 Slot spacing must be >= 0.14 um
4683 0 MSLOT4.W.1_MSLOT4.L.1: Metal4 Slot width/length must be >= 2.0 um
4685 0 MSLOT4.SP.1: Metal4 Slot to Metal4 Slot spacing must be >= 0.14 um
4687 0 MSLOT5.W.1_MSLOT5.L.1: Metal5 Slot width/length must be >= 2.0 um
4689 0 MSLOT5.SP.1: Metal5 Slot to Metal5 Slot spacing must be >= 0.14 um
4691 0 MSLOT6.W.1_MSLOT6.L.1: Metal6 Slot width/length must be >= 2.0 um
4693 0 MSLOT6.SP.1: Metal6 Slot to Metal6 Slot spacing must be >= 0.14 um
4695 0 MSLOT7.W.1_MSLOT7.L.1: Metal7 Slot width/length must be >= 2.0 um
4697 0 MSLOT7.SP.1: Metal7 Slot to Metal7 Slot spacing must be >= 0.14 um
4699 0 MSLOT8.W.1_MSLOT8.L.1: Metal8 Slot width/length must be >= 2.0 um
4701 0 MSLOT8.SP.1: Metal8 Slot to Metal8 Slot spacing must be >= 0.44 um
4703 0 MSLOT9.W.1_MSLOT9.L.1: Metal9 Slot width/length must be >= 2.0 um
4705 0 MSLOT9.SP.1: Metal9 Slot to Metal9 Slot spacing must be >= 0.44 um
4709 0 ESD.1: ESD gate width must be >= 15.0 um and <= 65.0 um
4710 0 ESD.4: N+ source should connect to Pad or Bulk
4711 0 ESD.4: P+ source should connect to Pad or Nwell
4712 0 ESD.5: NMOS I/O and ESD devices must be inside P+ rings
4713 0 ESD.6: PMOS I/O and ESD devices must be inside N+ rings
4714 0 ESD.7: P+ taps can NOT butt NMOS I/O and ESD devices
4715 0 ESD.7: N+ taps can NOT butt PMOS I/O and ESD devices
4716 0 ESD.8: N+ drains must be non-salicided (except Contact area)
4717 0 ESD.8: P+ drains must be non-salicided (except Contact area)
4720 0 ESD.11: SiProt to Poly gate overlap must be >= 0.05 um
4722 0 ESD.12: SiProt to Poly gate enclosure must be >= 1.8 um
4724 0 ESD.13: SiProt to Oxide overlap must be >= 1.8 um
4728 0 ESD.14: ESD gate length must be == 0.3 um
4732 0 ESD.15: Poly gate to Cont spacing must be >= 0.25 um
4733 0 ESD.15: Poly gate to Cont spacing must be >= 0.25 um
4735 0 BONDPAD.E.1: Metal1 to Bondpad enclosure must be >= 2.0 um
4737 0 BONDPAD.E.1: Metal1 to Bondpad enclosure must be >= 2.0 um
4738 0 BONDPAD.SP.2: Bondpad Metal1 to Metal1 spacing must be >= 3.0 um
4740 0 BONDPAD.E.1: Metal2 to Bondpad enclosure must be >= 2.0 um
4742 0 BONDPAD.E.1: Metal2 to Bondpad enclosure must be >= 2.0 um
4743 0 BONDPAD.SP.2: Bondpad Metal2 to Metal2 spacing must be >= 3.0 um
4745 0 BONDPAD.E.1: Metal3 to Bondpad enclosure must be >= 2.0 um
4747 0 BONDPAD.E.1: Metal3 to Bondpad enclosure must be >= 2.0 um
4748 0 BONDPAD.SP.2: Bondpad Metal3 to Metal3 spacing must be >= 3.0 um
4750 0 BONDPAD.E.1: Metal4 to Bondpad enclosure must be >= 2.0 um
4752 0 BONDPAD.E.1: Metal4 to Bondpad enclosure must be >= 2.0 um
4753 0 BONDPAD.SP.2: Bondpad Metal4 to Metal4 spacing must be >= 3.0 um
4755 0 BONDPAD.E.1: Metal5 to Bondpad enclosure must be >= 2.0 um
4757 0 BONDPAD.E.1: Metal5 to Bondpad enclosure must be >= 2.0 um
4758 0 BONDPAD.SP.2: Bondpad Metal5 to Metal5 spacing must be >= 3.0 um
4760 0 BONDPAD.E.1: Metal6 to Bondpad enclosure must be >= 2.0 um
4762 0 BONDPAD.E.1: Metal6 to Bondpad enclosure must be >= 2.0 um
4763 0 BONDPAD.SP.2: Bondpad Metal6 to Metal6 spacing must be >= 3.0 um
4765 0 BONDPAD.E.1: Metal7 to Bondpad enclosure must be >= 2.0 um
4767 0 BONDPAD.E.1: Metal7 to Bondpad enclosure must be >= 2.0 um
4768 0 BONDPAD.SP.2: Bondpad Metal7 to Metal7 spacing must be >= 3.0 um
4770 0 BONDPAD.E.1: Metal8 to Bondpad enclosure must be >= 2.0 um
4772 0 BONDPAD.E.1: Metal8 to Bondpad enclosure must be >= 2.0 um
4773 0 BONDPAD.SP.2: Bondpad Metal8 to Metal8 spacing must be >= 3.0 um
4775 0 BONDPAD.E.1: Metal9 to Bondpad enclosure must be >= 2.0 um
4777 0 BONDPAD.E.1: Metal9 to Bondpad enclosure must be >= 2.0 um
4778 0 BONDPAD.SP.2: Bondpad Metal9 to Metal9 spacing must be >= 3.0 um
4781 0 BONDPAD.W.1: Bondpad width must be >= 52.0 um
4783 0 BONDPAD.W.1: Bondpad width must be >= 52.0 um
4785 0 BONDPAD.SP.1: Bondpad to Bondpad spacing must be >= 8.0 um
4787 0 BONDPAD.B.1: Bondpad Metal1 beveled segments must be >= 1.8 um and <= 3.2 um
4789 0 BONDPAD.B.1: Bondpad Metal2 beveled segments must be >= 1.8 um and <= 3.2 um
4791 0 BONDPAD.B.1: Bondpad Metal3 beveled segments must be >= 1.8 um and <= 3.2 um
4793 0 BONDPAD.B.1: Bondpad Metal4 beveled segments must be >= 1.8 um and <= 3.2 um
4795 0 BONDPAD.B.1: Bondpad Metal5 beveled segments must be >= 1.8 um and <= 3.2 um
4797 0 BONDPAD.B.1: Bondpad Metal6 beveled segments must be >= 1.8 um and <= 3.2 um
4799 0 BONDPAD.B.1: Bondpad Metal7 beveled segments must be >= 1.8 um and <= 3.2 um
4801 0 BONDPAD.B.1: Bondpad Metal8 beveled segments must be >= 1.8 um and <= 3.2 um
4803 0 BONDPAD.B.1: Bondpad Metal9 beveled segments must be >= 1.8 um and <= 3.2 um
4806 0 BONDPAD.SP.3: Bondpad Via1 to Bondpad Via1 spacing must be >= 0.22 um
4809 0 BONDPAD.SP.3: Bondpad Via2 to Bondpad Via2 spacing must be >= 0.22 um
4812 0 BONDPAD.SP.3: Bondpad Via3 to Bondpad Via3 spacing must be >= 0.22 um
4815 0 BONDPAD.SP.3: Bondpad Via4 to Bondpad Via4 spacing must be >= 0.22 um
4818 0 BONDPAD.SP.3: Bondpad Via5 to Bondpad Via5 spacing must be >= 0.22 um
4821 0 BONDPAD.SP.3: Bondpad Via6 to Bondpad Via6 spacing must be >= 0.22 um
4824 0 BONDPAD.SP.4: Bondpad Via7 to Bondpad Via7 spacing must be >= 0.54 um
4827 0 BONDPAD.SP.4: Bondpad Via8 to Bondpad Via8 spacing must be >= 0.54 um
4829 0 BONDPAD.E.2: Bondpad Metal1 to Via1 enclosure must be >= 0.05 um
4831 0 BONDPAD.E.2: Bondpad Metal1 to Via1 enclosure must be >= 0.05 um
4833 0 BONDPAD.E.2: Bondpad Metal2 to Via2 enclosure must be >= 0.05 um
4835 0 BONDPAD.E.2: Bondpad Metal2 to Via2 enclosure must be >= 0.05 um
4837 0 BONDPAD.E.2: Bondpad Metal3 to Via3 enclosure must be >= 0.05 um
4839 0 BONDPAD.E.2: Bondpad Metal3 to Via3 enclosure must be >= 0.05 um
4841 0 BONDPAD.E.2: Bondpad Metal4 to Via4 enclosure must be >= 0.05 um
4843 0 BONDPAD.E.2: Bondpad Metal4 to Via4 enclosure must be >= 0.05 um
4845 0 BONDPAD.E.2: Bondpad Metal5 to Via5 enclosure must be >= 0.05 um
4847 0 BONDPAD.E.2: Bondpad Metal5 to Via5 enclosure must be >= 0.05 um
4849 0 BONDPAD.E.2: Bondpad Metal6 to Via6 enclosure must be >= 0.05 um
4851 0 BONDPAD.E.2: Bondpad Metal6 to Via6 enclosure must be >= 0.05 um
4853 0 BONDPAD.E.3: Bondpad Metal7 to Via7 enclosure must be >= 0.09 um
4855 0 BONDPAD.E.3: Bondpad Metal7 to Via7 enclosure must be >= 0.09 um
4857 0 BONDPAD.E.3: Bondpad Metal8 to Via8 enclosure must be >= 0.09 um
4859 0 BONDPAD.E.3: Bondpad Metal8 to Via8 enclosure must be >= 0.09 um
4861 0 BONDPAD.E.2: Bondpad Metal2 to Via1 enclosure must be >= 0.05 um
4863 0 BONDPAD.E.2: Bondpad Metal2 to Via1 enclosure must be >= 0.05 um
4865 0 BONDPAD.E.2: Bondpad Metal3 to Via2 enclosure must be >= 0.05 um
4867 0 BONDPAD.E.2: Bondpad Metal3 to Via2 enclosure must be >= 0.05 um
4869 0 BONDPAD.E.2: Bondpad Metal4 to Via3 enclosure must be >= 0.05 um
4871 0 BONDPAD.E.2: Bondpad Metal4 to Via3 enclosure must be >= 0.05 um
4873 0 BONDPAD.E.2: Bondpad Metal5 to Via4 enclosure must be >= 0.05 um
4875 0 BONDPAD.E.2: Bondpad Metal5 to Via4 enclosure must be >= 0.05 um
4877 0 BONDPAD.E.2: Bondpad Metal6 to Via5 enclosure must be >= 0.05 um
4879 0 BONDPAD.E.2: Bondpad Metal6 to Via5 enclosure must be >= 0.05 um
4881 0 BONDPAD.E.2: Bondpad Metal7 to Via6 enclosure must be >= 0.05 um
4883 0 BONDPAD.E.2: Bondpad Metal7 to Via6 enclosure must be >= 0.05 um
4885 0 BONDPAD.E.3: Bondpad Metal8 to Via7 enclosure must be >= 0.09 um
4887 0 BONDPAD.E.3: Bondpad Metal8 to Via7 enclosure must be >= 0.09 um
4889 0 BONDPAD.E.3: Bondpad Metal9 to Via8 enclosure must be >= 0.09 um
4891 0 BONDPAD.E.3: Bondpad Metal9 to Via8 enclosure must be >= 0.09 um
4892 0 BONDPAD.SP.6: Bondpad Metal1 to Bondpad Metal1 spacing across first slot must be >= 1.00 um and <= 3.50 um
4893 0 BONDPAD.SP.6: Bondpad Metal1 to Bondpad Metal1 spacing across first slot must be >= 1.00 um and <= 3.50 um
4894 0 BONDPAD.SP.6: Bondpad Metal2 to Bondpad Metal2 spacing across first slot must be >= 1.00 um and <= 3.50 um
4895 0 BONDPAD.SP.6: Bondpad Metal2 to Bondpad Metal2 spacing across first slot must be >= 1.00 um and <= 3.50 um
4896 0 BONDPAD.SP.6: Bondpad Metal3 to Bondpad Metal3 spacing across first slot must be >= 1.00 um and <= 3.50 um
4897 0 BONDPAD.SP.6: Bondpad Metal3 to Bondpad Metal3 spacing across first slot must be >= 1.00 um and <= 3.50 um
4898 0 BONDPAD.SP.6: Bondpad Metal4 to Bondpad Metal4 spacing across first slot must be >= 1.00 um and <= 3.50 um
4899 0 BONDPAD.SP.6: Bondpad Metal4 to Bondpad Metal4 spacing across first slot must be >= 1.00 um and <= 3.50 um
4900 0 BONDPAD.SP.6: Bondpad Metal5 to Bondpad Metal5 spacing across first slot must be >= 1.00 um and <= 3.50 um
4901 0 BONDPAD.SP.6: Bondpad Metal5 to Bondpad Metal5 spacing across first slot must be >= 1.00 um and <= 3.50 um
4902 0 BONDPAD.SP.6: Bondpad Metal6 to Bondpad Metal6 spacing across first slot must be >= 1.00 um and <= 3.50 um
4903 0 BONDPAD.SP.6: Bondpad Metal6 to Bondpad Metal6 spacing across first slot must be >= 1.00 um and <= 3.50 um
4904 0 BONDPAD.SP.6: Bondpad Metal7 to Bondpad Metal7 spacing across first slot must be >= 1.00 um and <= 3.50 um
4905 0 BONDPAD.SP.6: Bondpad Metal7 to Bondpad Metal7 spacing across first slot must be >= 1.00 um and <= 3.50 um
4906 0 BONDPAD.SP.6: Bondpad Metal8 to Bondpad Metal8 spacing across first slot must be >= 1.00 um and <= 3.50 um
4907 0 BONDPAD.SP.6: Bondpad Metal8 to Bondpad Metal8 spacing across first slot must be >= 1.00 um and <= 3.50 um
4909 0 BONDPAD.SP.7: Bondpad Via1 array to Bondpad Via1 array spacing must be >= 1.1 um
4911 0 BONDPAD.SP.7: Bondpad Via2 array to Bondpad Via2 array spacing must be >= 1.1 um
4913 0 BONDPAD.SP.7: Bondpad Via3 array to Bondpad Via3 array spacing must be >= 1.1 um
4915 0 BONDPAD.SP.7: Bondpad Via4 array to Bondpad Via4 array spacing must be >= 1.1 um
4917 0 BONDPAD.SP.7: Bondpad Via5 array to Bondpad Via5 array spacing must be >= 1.1 um
4919 0 BONDPAD.SP.7: Bondpad Via6 array to Bondpad Via6 array spacing must be >= 1.1 um
4921 0 BONDPAD.SP.7: Bondpad Via7 array to Bondpad Via7 array spacing must be >= 1.1 um
4923 0 BONDPAD.SP.7: Bondpad Via8 array to Bondpad Via8 array spacing must be >= 1.1 um
4926 0 OXIDER.W.1.1: Oxide resistor width must be >= 0.2 um
4929 0 POLYR.W.1.1: Poly resistor width must be >= 0.2 um
